### ISSUE TITLE
min-content

### ISSUE THREAD

**Issue by vasilisvg** [sayLISA/CSS-TO-THE-RESCUE#5]
Wat gebeurt er als ik de `min-content` hier weghaal? Waarom staat hij hier precies?

https://github.com/sayLISA/CSS-TO-THE-RESCUE/blob/master/week%202/css/style.css#L216

**Comment by sayLISA** [comment]
Als je de min-content weghaalt wordt de max-width van de figure 30em, die ik als fallback heb gezet. De min-content zorgt ervoor dat de figure de width aanneemt van het grootste element erin (in dit geval de image) zodat de tekst die eronder staat altijd mooi meeschaalt.
